[
  {
    geonameid: "",
    city: "New York",
    country: "United States",
    urban_area: "",
    urban_area_url_exists: false,
    population: "",
    coordinates: {
      latitude: "",
      longitude: "",
    },
    photo_url: "https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg",
    desktop_img: "https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg",
    mobile_img: "https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg",
    status: "Want to go",
    date: "",
    notes: "",
  },
  {
    geonameid: "",
    city: "Sydney",
    country: "Australia",
    urban_area: "",
    urban_area_url_exists: false,
    population: "",
    coordinates: {
      latitude: "",
      longitude: "",
    },
    photo_url: "https://i.natgeofe.com/n/bd48279e-be5a-4f28-9551-5cb917c6766e/GettyImages-103455489cropped.jpg",
    desktop_img: "https://i.natgeofe.com/n/bd48279e-be5a-4f28-9551-5cb917c6766e/GettyImages-103455489cropped.jpg",
    mobile_img: "https://i.natgeofe.com/n/bd48279e-be5a-4f28-9551-5cb917c6766e/GettyImages-103455489cropped.jpg",
    status: "Visited",
    date: "",
    notes: "",
  },
  {
    geonameid: "",
    city: "Rio de Janeiro",
    country: "Brazil",
    urban_area: "",
    urban_area_url_exists: false,
    population: "",
    coordinates: {
      latitude: "",
      longitude: "",
    },
    photo_url:
      "https://www.travelandleisure.com/thmb/x-LBqpaBsbUqGYtHu8gLnRMxPvg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/rio-de-janeiro-RIOTG0721-c59c5e2f3a354e798587d5ef925b23e3.jpg",
    desktop_img:
      "https://www.travelandleisure.com/thmb/x-LBqpaBsbUqGYtHu8gLnRMxPvg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/rio-de-janeiro-RIOTG0721-c59c5e2f3a354e798587d5ef925b23e3.jpg",
    mobile_img:
      "https://www.travelandleisure.com/thmb/x-LBqpaBsbUqGYtHu8gLnRMxPvg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/rio-de-janeiro-RIOTG0721-c59c5e2f3a354e798587d5ef925b23e3.jpg",
    status: "Visited",
    date: "",
    notes: "",
  },
  {
    geonameid: "",
    city: "Cape Town",
    country: "South Africa",
    urban_area: "",
    urban_area_url_exists: false,
    population: "",
    coordinates: {
      latitude: "",
      longitude: "",
    },
    photo_url: "https://cdn.britannica.com/42/126842-050-0803BC41/Sea-Point-Cape-Town-SAf.jpg",
    desktop_img: "https://cdn.britannica.com/42/126842-050-0803BC41/Sea-Point-Cape-Town-SAf.jpg",
    mobile_img: "https://cdn.britannica.com/42/126842-050-0803BC41/Sea-Point-Cape-Town-SAf.jpg",
    status: "Visited",
    date: "",
    notes: "",
  },
  {
    geonameid: "",
    city: "London",
    country: "United Kingdom",
    urban_area: "",
    urban_area_url_exists: false,
    population: "",
    coordinates: {
      latitude: "",
      longitude: "",
    },
    photo_url: "https://assets.editorial.aetnd.com/uploads/2019/03/topic-london-gettyimages-760251843-feature.jpg",
    desktop_img: "https://assets.editorial.aetnd.com/uploads/2019/03/topic-london-gettyimages-760251843-feature.jpg",
    mobile_img: "https://assets.editorial.aetnd.com/uploads/2019/03/topic-london-gettyimages-760251843-feature.jpg",
    status: "Visited",
    date: "",
    notes: "",
  },
  {
    geonameid: "",
    city: "Beijing",
    country: "China",
    urban_area: "",
    urban_area_url_exists: false,
    population: "",
    coordinates: {
      latitude: "",
      longitude: "",
    },
    photo_url: "https://travel2next.com/wp-content/uploads/beijing-night.jpg",
    desktop_img: "https://travel2next.com/wp-content/uploads/beijing-night.jpg",
    mobile_img: "https://travel2next.com/wp-content/uploads/beijing-night.jpg",
    status: "Visited",
    date: "",
    notes: "",
  },
  {
    geonameid: "",
    city: "Mumbai",
    country: "India",
    urban_area: "",
    urban_area_url_exists: false,
    population: "",
    coordinates: {
      latitude: "",
      longitude: "",
    },
    photo_url: "https://images.contentstack.io/v3/assets/blt00454ccee8f8fe6b/blt3f1dd78cb088d203/61d6b8af0d4d1813c7f45eb5/US_Mumbai_IN_Header.jpg",
    desktop_img: "https://images.contentstack.io/v3/assets/blt00454ccee8f8fe6b/blt3f1dd78cb088d203/61d6b8af0d4d1813c7f45eb5/US_Mumbai_IN_Header.jpg",
    mobile_img: "https://images.contentstack.io/v3/assets/blt00454ccee8f8fe6b/blt3f1dd78cb088d203/61d6b8af0d4d1813c7f45eb5/US_Mumbai_IN_Header.jpg",
    status: "Want to go",
    date: "",
    notes: "",
  },
  {
    geonameid: "",
    city: "Mexico City",
    country: "Mexico",
    urban_area: "",
    urban_area_url_exists: false,
    population: "",
    coordinates: {
      latitude: "",
      longitude: "",
    },
    photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Mexico_City_Reforma_Street.jpg/800px-Mexico_City_Reforma_Street.jpg",
    desktop_img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Mexico_City_Reforma_Street.jpg/800px-Mexico_City_Reforma_Street.jpg",
    mobile_img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Mexico_City_Reforma_Street.jpg/800px-Mexico_City_Reforma_Street.jpg",
    status: "Want to go",
    date: "",
    notes: "",
  },
  {
    geonameid: "",
    city: "Bangkok",
    country: "Thailand",
    urban_area: "",
    urban_area_url_exists: false,
    population: "",
    coordinates: {
      latitude: "",
      longitude: "",
    },
    photo_url: "https://content.r9cdn.net/rimg/dimg/26/5b/01e97574-city-26166-1592813274a.jpg?width=1366&height=768&xhint=1038&yhint=725&crop=true",
    desktop_img: "https://content.r9cdn.net/rimg/dimg/26/5b/01e97574-city-26166-1592813274a.jpg?width=1366&height=768&xhint=1038&yhint=725&crop=true",
    mobile_img: "https://content.r9cdn.net/rimg/dimg/26/5b/01e97574-city-26166-1592813274a.jpg?width=1366&height=768&xhint=1038&yhint=725&crop=true",
    status: "Going",
    date: "",
    notes: "",
  },
  {
    geonameid: "",
    city: "Istanbul",
    country: "Turkey",
    urban_area: "",
    urban_area_url_exists: false,
    population: "",
    coordinates: {
      latitude: "",
      longitude: "",
    },
    photo_url: "https://a.cdn-hotels.com/gdcs/production6/d781/3bae040b-2afb-4b11-9542-859eeb8ebaf1.jpg",
    desktop_img: "https://a.cdn-hotels.com/gdcs/production6/d781/3bae040b-2afb-4b11-9542-859eeb8ebaf1.jpg",
    mobile_img: "https://a.cdn-hotels.com/gdcs/production6/d781/3bae040b-2afb-4b11-9542-859eeb8ebaf1.jpg",
    status: "Visited",
    date: "",
    notes: "",
  },
  {
    geonameid: "",
    city: "Dubai",
    country: "United Arab Emirates",
    urban_area: "",
    urban_area_url_exists: false,
    population: "",
    coordinates: {
      latitude: "",
      longitude: "",
    },
    photo_url: "https://www.visitdubai.com/-/media/gathercontent/poi/b/burj-khalifa/fallback-image/poi-burj-khalifa-3-dtcm-jun-2023.jpg",
    desktop_img: "https://www.visitdubai.com/-/media/gathercontent/poi/b/burj-khalifa/fallback-image/poi-burj-khalifa-3-dtcm-jun-2023.jpg",
    mobile_img: "https://www.visitdubai.com/-/media/gathercontent/poi/b/burj-khalifa/fallback-image/poi-burj-khalifa-3-dtcm-jun-2023.jpg",
    status: "Want to go",
    date: "",
    notes: "",
  },
  {
    geonameid: "",
    city: "Berlin",
    country: "Germany",
    urban_area: "",
    urban_area_url_exists: false,
    population: "",
    coordinates: {
      latitude: "",
      longitude: "",
    },
    photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Museumsinsel_Berlin_Juli_2021_1_%28cropped%29.jpg/1200px-Museumsinsel_Berlin_Juli_2021_1_%28cropped%29.jpg",
    desktop_img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Museumsinsel_Berlin_Juli_2021_1_%28cropped%29.jpg/1200px-Museumsinsel_Berlin_Juli_2021_1_%28cropped%29.jpg",
    mobile_img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Museumsinsel_Berlin_Juli_2021_1_%28cropped%29.jpg/1200px-Museumsinsel_Berlin_Juli_2021_1_%28cropped%29.jpg",
    status: "Going",
    date: "",
    notes: "",
  },
  {
    geonameid: "",
    city: "Venice",
    country: "Italy",
    urban_area: "",
    urban_area_url_exists: false,
    population: "",
    coordinates: {
      latitude: "",
      longitude: "",
    },
    photo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Santa_Maria_della_Salute_%2850428075772%29.jpg/1200px-Santa_Maria_della_Salute_%2850428075772%29.jpg",
    desktop_img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Santa_Maria_della_Salute_%2850428075772%29.jpg/1200px-Santa_Maria_della_Salute_%2850428075772%29.jpg",
    mobile_img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Santa_Maria_della_Salute_%2850428075772%29.jpg/1200px-Santa_Maria_della_Salute_%2850428075772%29.jpg",
    status: "Visited",
    date: "",
    notes: "",
  },
  {
    geonameid: "",
    city: "Buenos Aires",
    country: "Argentina",
    urban_area: "",
    urban_area_url_exists: false,
    population: "",
    coordinates: {
      latitude: "",
      longitude: "",
    },
    photo_url: "https://cdn.britannica.com/63/188963-050-2C94FEC2/Night-view-obelisk-Buenos-Aires.jpg",
    desktop_img: "https://cdn.britannica.com/63/188963-050-2C94FEC2/Night-view-obelisk-Buenos-Aires.jpg",
    mobile_img: "https://cdn.britannica.com/63/188963-050-2C94FEC2/Night-view-obelisk-Buenos-Aires.jpg",
    status: "Visited",
    date: "",
    notes: "",
  },
  {
    geonameid: "",
    city: "Rome",
    country: "Italy",
    urban_area: "",
    urban_area_url_exists: false,
    population: "",
    coordinates: {
      latitude: "",
      longitude: "",
    },
    photo_url: "https://www.fodors.com/wp-content/uploads/2018/10/HERO_UltimateRome_Hero_shutterstock789412159.jpg",
    desktop_img: "https://www.fodors.com/wp-content/uploads/2018/10/HERO_UltimateRome_Hero_shutterstock789412159.jpg",
    mobile_img: "https://www.fodors.com/wp-content/uploads/2018/10/HERO_UltimateRome_Hero_shutterstock789412159.jpg",
    status: "Visited",
    date: "",
    notes: "",
  },
  {
    geonameid: "",
    city: "Paris",
    country: "France",
    urban_area: "",
    urban_area_url_exists: false,
    population: "",
    coordinates: {
      latitude: "",
      longitude: "",
    },
    photo_url:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_août_2014_%282%29.jpg/1200px-La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_août_2014_%282%29.jpg",
    desktop_img:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_août_2014_%282%29.jpg/1200px-La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_août_2014_%282%29.jpg",
    mobile_img:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_août_2014_%282%29.jpg/1200px-La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_août_2014_%282%29.jpg",
    status: "Visited",
    date: "",
    notes: "",
  },
];
